name: Build and Push to Artifact Registry

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: prj-vertexai-test
  REGION: asia-southeast1
  REPOSITORY: asia-southeast1-docker.pkg.dev/prj-vertexai-test/default
  IMAGE_NAME: runner
  WIF_PROVIDER: projects/868042038328/locations/global/workloadIdentityPools/github/providers/github
  WIF_SA: github-actions-deployer@prj-vertexai-test.iam.gserviceaccount.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ env.WIF_PROVIDER }}'
        service_account: '${{ env.WIF_SA }}'

    - name: Docker Auth
      uses: 'docker/login-action@v3'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.REGION }}-docker.pkg.dev'

    - name: Generate requirements.txt
      run: |
        uv export --format requirements.txt --output-file requirements.txt --no-dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
